# Additional SonarCloud settings
sonar.links.homepage=https://github.com/sonar-brettmiller/hackathon-starter
sonar.links.ci=https://github.com/sonar-brettmiller/hackathon-starter/actions
sonar.links.scm=https://github.com/sonar-brettmiller/hackathon-starter
sonar.links.issue=https://github.com/sonar-brettmiller/hackathon-starter/issues